spring:
  application:
    name: Roamance
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  main:
    banner-mode: off

application:
  frontend:
    url: ${FRONTEND_URL}
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000
  gemini:
    api-key: ${GEMINI_API_KEY}
  nomic:
    api-key: ${NOMIC_API_KEY}
  pgvector:
    host: ${PGVECTOR_HOST}
    port: ${PGVECTOR_PORT}
    db: ${PGVECTOR_DB}
    user: ${PGVECTOR_USER}
    password: ${PGVECTOR_PASSWORD}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    root: warn
    com.devs.roamance: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true
