spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: false
  main:
    banner-mode: off

logging:
  level:
    root: warn
    com.devs.roamance: info

application:
  frontend:
    url: http://localhost:3000
  security:
    jwt:
      secret: testsecret
      access-token-expiration: 3600000
      refresh-token-expiration: 86400000
  gemini:
    api-key: sdlkfnsdlk
  nomic:
    api-key: asdfasdsdf
  pgvector:
    host: asdas
    port: 2313
    db: sdfdfgv
    user: as3ds
    password: ""
