name: Spotless Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches:
      - develop

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck